name: terraform-plan
description: Leverages `dflook/terraform-plan` to run Terraform plan using Terraform Enterprise/Cloud and OSS
inputs:
  var_file:
    description: Path to a Terraform variable file
    required: true
  tfe_org:
    description: The organization that stores the state file for the Terraform code base
    required: false
    default: ''
  tfe_workspace:
    description: The TFE/TFC workspace that stores the state file for the Terraform code base
    required: false
    default: ''
  tfe_token:
    description: Authentication token for tfe/tfc
    required: false
    default: ''
  backend_config:
    description: Backend configuration for Terraform remote state
    required: false
    default: ''
  destroy:
    description: Whether to destroy or not
    required: false
    default: 'false'
  path:
    description: Path of configuration files
    required: false
    default: .


runs:
  using: composite
  steps:
      - name: Terraform Plan - OSS
        uses: dflook/terraform-plan@a8d7e66e63aff79825a46e3374c4fd66ff9ce543
        id: terraform-plan-os-no-backend-config
        if: ${{ inputs.tfe_workspace == ''  && inputs.backend_config == '' }}
        with:
          path: ${{ inputs.path }}
          var_file: ${{ inputs.var_file }}
          destroy: ${{ inputs.destroy }}

      - name: Terraform Plan - OSS
        uses: dflook/terraform-plan@a8d7e66e63aff79825a46e3374c4fd66ff9ce543
        id: terraform-plan-os-backend-config
        if: ${{ inputs.tfe_workspace == ''  && inputs.backend_config != '' }}
        with:
          path: ${{ inputs.path }}
          var_file: ${{ inputs.var_file }}
          destroy: ${{ inputs.destroy }}
          backend_config: |
            ${{ inputs.backend_config }}


      - name: Terraform Plan - TFE
        uses: dflook/terraform-plan@a8d7e66e63aff79825a46e3374c4fd66ff9ce543
        id: terraform-plan-tfe
        if: ${{ inputs.tfe_workspace != '' }}
        env:
          TERRAFORM_CLOUD_TOKENS: ${{ inputs.tfe_org }}=${{ inputs.tfe_token }}
        with:
          path: ${{ inputs.path }}
          workspace: ${{ inputs.tfe_workspace }}
          var_file: ${{ inputs.var_file }}
          destroy: ${{ inputs.destroy }}
